export const Locators = {
  createrequestaddButton: "//div[@class='dicon dicon-add icon-leftspace text-primary']", 
  Singlerequest: "//aoui-dropdown-item[1]",
  engagementselection: "(//datatable-body-cell)[1]",
  projectSelection: "//datatable-body-cell[1]/div[1]",
  thirdDropdown: "(//span[@class='aoui-select-selection__rendered ng-star-inserted'])[2]",
  searchField: "//input[@class='aoui-select-search__field']",
  resultOption: "//div[@class='aoui-select-results__option-label ng-star-inserted']",
  confirmButton: "//button[normalize-space()='CONFIRM']",
  radioPcaobFalse: "#radio-pcaobfalse",
  radioPcaobFalseLabel: "//label[@for='radio-pcaobfalse']",
  requestDetailsTab: "//span[normalize-space()='Request Details']",
  entityDropdown: "//div[@id='EntityNameDropdown']//span[@class='aoui-select-selection aoui-select-selection--single']",
  EntityNameDropdown: "#EntityNameDropdown",
  chargeCodeTextbox: "#RequestChargeCodeValue",
  chargeCodeListItem: "#RequestChargeCodeValue",
  chargeCodeText: '100115ChargeCode 1 | QA - Sam',
  dataduedatecalendarSelector: "//aoui-datepicker[@id='data-due-date']//input",
  requestDueDateCalendarSelector: "//aoui-datepicker[@id='request-due-date']//input",
  phasedropdown: "//aoui-select[@class='ng-star-inserted']//span[@class='aoui-select-selection__rendered ng-star-inserted']",
  phaseselection: "//div[contains(text(),'Planning')]",
  partnerDropdown: "aoui-etm-select[id='lead-engagement-partner'] div span[class='aoui-select-selection__placeholder']",
  ManagerDropdown: "aoui-etm-select[id='lead-engagement-manager'] div span[class='aoui-select-selection__placeholder']",
  projectmanager: "//request-contact-component[@class='ng-star-inserted']//div[@class='ng-star-inserted']//div//div[1]",
  managerSelection: "//div[@role='option']",
  filtericon: "//div[@class='dicon dicon-filter icon-leftspace text-primary']",
  fiterdropdown: "//span[@class='aoui-select-selection__rendered ng-star-inserted']",
  japaneseLanguage: "中文(台灣)",
 
Lastcell: "body > ems-app:nth-child(2) > nova-master:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > data-extract-home:nth-child(2) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > data-extract-list:nth-child(1) > div:nth-child(2) > aoui-table:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(5)",
ReloadButton:"//div[@class='dicon dicon-reload-nc text-normal']",
ManageRequesttypesGrid:"(//label[contains(text(),'Edit')])[1]",
Actiondropdown: "#btn-actions aoui-dicon div",
LevviEngagementSelection: ".datatable-body-cell",
ActionDropdownEntities:"(//div[@class='dicon dicon-down-arrow-nc icon-leftspace text-primary'])[2]",
IdentifyEntities:"//aoui-dropdown-item[1]",
Deliverycentercancelbutton:"//button[@type='button'][normalize-space()='Cancel']",
settingicon:"#nav-list-item-admin-settings",
ManageRequesttypes:"#submenu-item-global-requests",
FeatureEnablement:"#submenu-item-audit-online-feature-enablement",
memberfirm:"text=Member Firm",
memberfirmtextbox:"(//input[@type='text'])[1]",
Applybutton:"//div[@class='dropdown-menu filter-dropdown show']//button[@class='btn btn-primary filter-button'][normalize-space()='Apply']",
popup:"//button[@class='onetrust-close-btn-handler banner-close-button ot-close-icon']",
initial: "//div[@class='user-initials']",
languagedropdown: ".aoui-select-selection__arrow",
EnglishLanguage: "//div[@title='English (United States)']",
fiterdropdownOptions: "//ul[@class='aoui-select-results__options']",
requestUpdatedsucessPopup: "text=Your request has been updated successfully",
ADCPortalReporting: "text=ADC Portal Reporting",
requestListDropDown: "div[class='row'] span:nth-child(2)",
SelectRequestlist: ".select2-results__option.ng-star-inserted",
SubmitRequestType: ".component-aoui-button",
 DataExtractFirstcell:"div[class='aoui-tableRowsContainer'] div:nth-child(1) div:nth-child(1)",
DataExtractLastcell: "div[class='aoui-tableRowsContainer'] div:nth-child(1) div:nth-child(5)",


};
