// Code Generated by Sidekick is for learning and experimentation purposes only.
import { Page } from "playwright";

export default class LoginPage {
    private page: Page;

    constructor(page: Page) {
        this.page = page;
    }

    // Use Locator API
    public get eleEmailTextField() {
        return this.page.locator('#i0116');
    }
    public get nextButton() {
        return this.page.locator('#idSIButton9');
    }

    public get elePassTextField() {
        return this.page.locator('#i0118');
    }

    public get eleSignBtn() {
        return this.page.locator('#idSIButton9');
    }

    public async enterUserName(email: string) {
        await this.eleEmailTextField.fill(email);
    }
    public async nxtButton() {
        await this.nextButton.click();
    }

    public async enterUserPassword(password: string) {
        await this.elePassTextField.fill(password);
    }

    public async clickSignBtn() {
        await this.eleSignBtn.click();
    }

    public async login(email: string, password: string) {
        await this.enterUserName(email);
        await this.enterUserPassword(password);
        await this.clickSignBtn();
        
    }
}
