// Code Generated by Sidekick is for learning and experimentation purposes only.
import { Page, test } from '@playwright/test';
import { attachment } from 'allure-js-commons';

export default class ReportUtils {

    public static async screenshot(page: Page, description?: string) {
        const screenshotBuffer = await page.screenshot();
        description = description ?? "screenshot";
        // Attach screenshot to Playwright report
        test.info().attach(description, {
            body: screenshotBuffer,
            contentType: 'image/png'
        });
        // Attach screenshot to Allure report
        attachment(description, screenshotBuffer, 'image/png');
    }

    public static async attachVideo(page: Page, description?: string) {
        // Wait until the page is closed to ensure the video is saved
        const video = page.video();
        if (video) {
            const videoPath = await video.path();
            description = description ?? "video";
            // Attach video to Playwright report
            test.info().attach(description, {
                path: videoPath,
                contentType: 'video/webm'
            });
        }
    }
}

